main : 
  render : False
  epsilon : 0.1
  delta : 0.0001
  alpha : 0.5
  gamma : 0.95
  max_step : 10000
  nb_episode : 1000
  nb_execution : 100


sr : 
  env9x6 : 
    train_episode_length : 40
    test_episode_length : 20
  env18x12 : 
    train_episode_length : 200
    test_episode_length : 100
  env36x24 : 
    train_episode_length : 1000
    test_episode_length : 500

test :
  render : False
  epsilon : 0.5
  delta : 0.0001
  alpha : 0.5
  gamma : 0.95
  max_step : 500
  nb_episode : 100
  nb_execution : 20
  train_episode_length : 200
  test_episode_length : 20