main : 
  render : False
  epsilon : 0.5
  delta : 0.01
  alpha : 0.5
  max_step : 1000
  episode : 2000

sr : 
  episode : 500
  small : 
    train_episode_length : 1000
    test_episode_length : 200
  grand : 
    train_episode_length : 4000
    test_episode_length : 10000