main : 
  render : False
  epsilon : 0.5
  delta : 0.0001
  alpha : 0.5
  gamma : 0.95
  max_step : 2000
  nb_episode : 500
  nb_execution : 100


sr : 
  nb_episode : 50
  small : 
    train_episode_length : 200
    test_episode_length : 20
  grand : 
    # train_episode_length : 1000
    # test_episode_length : 80
    train_episode_length : 1000
    test_episode_length : 80


test :
  render : false
  epsilon : 0.5
  delta : 0.0001
  alpha : 0.5
  gamma : 0.95
  max_step : 500
  nb_episode : 200
  nb_execution : 5
  train_episode_length : 200
  test_episode_length : 20