main : 
  render : False
  epsilon : 0.5
  delta : 0.0001
  alpha : 0.5
  gamma : 0.95
  max_step : 500
  nb_episode : 20
  nb_execution : 3


sr : 
  nb_episode : 50
  small : 
    train_episode_length : 200
    test_episode_length : 20
  grand : 
    train_episode_length : 1000
    test_episode_length : 80

