main : 
  render : False
  epsilon : 0.5
  delta : 0.0001
  alpha : 0.5
  max_step : 500
  episode : 2000

sr : 
  episode : 50
  small : 
    train_episode_length : 200
    test_episode_length : 20
  grand : 
    train_episode_length : 4000
    test_episode_length : 10000